version: "3.9"

services:
  game_server_build:
    image: game_server
    build:
      context: .
      dockerfile: game_server/Dockerfile
    env_file:
      - game_server/.env
  client:
    image: client
    build:
      context: .
      dockerfile: client/Dockerfile
  mongodb:
    image: mongo
    ports:
      - "27016:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: scooby
    volumes:
      - mongodb:/data/db
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
  server:
    image: server
    build:
      context: .
      dockerfile: server/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - server/.env
    depends_on:
      - nginx
      - mongodb
volumes:
  mongodb: null
